<?php

class ControlesTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('controles')->insert(array(
		  	array('codigo' => 'A.05.01.01','nombre' => 'Políticas para la seguridad de la información'),
			array('codigo' => 'A.05.01.02','nombre' => 'Revisión de las políticas de seguridad de la información'),
			array('codigo' => 'A.06.01.01','nombre' => 'Roles y responsabilidades de la seguridad de la información'),
			array('codigo' => 'A.06.01.02','nombre' => 'Segregación de funciones'),
			array('codigo' => 'A.06.01.03','nombre' => 'Contacto con autoridades'),
			array('codigo' => 'A.06.01.04','nombre' => 'Contacto con grupos especiales de interés'),
			array('codigo' => 'A.06.01.05','nombre' => 'Seguridad de la información en la gestión de proyecto'),
			array('codigo' => 'A.06.02.01','nombre' => 'Política de dispositivos móviles'),
			array('codigo' => 'A.06.02.02','nombre' => 'Trabajo remoto'),
			array('codigo' => 'A.07.01.01','nombre' => 'Selección'),
			array('codigo' => 'A.07.01.02','nombre' => 'Términos y condiciones de la relación laboral'),
			array('codigo' => 'A.07.02.01','nombre' => 'Responsabilidades de la dirección'),
			array('codigo' => 'A.07.02.02','nombre' => 'Concientización, educación y formación en seguridad de la información'),
			array('codigo' => 'A.07.02.03','nombre' => 'Proceso disciplinario'),
			array('codigo' => 'A.07.03.01','nombre' => 'Responsabilidades en la desvinculación o cambio de empleo'),
			array('codigo' => 'A.08.01.01','nombre' => 'Inventario de activos'),
			array('codigo' => 'A.08.01.02','nombre' => 'Propiedad de los activos'),
			array('codigo' => 'A.08.01.03','nombre' => 'Uso aceptable de los activos'),
			array('codigo' => 'A.08.01.04','nombre' => 'Devolución de activos'),
			array('codigo' => 'A.08.02.01','nombre' => 'Clasificación de la información'),
			array('codigo' => 'A.08.02.02','nombre' => 'Etiquetado de la información'),
			array('codigo' => 'A.08.02.03','nombre' => 'Manejo de activos'),
			array('codigo' => 'A.08.03.01','nombre' => 'Gestión de los medios removibles'),
			array('codigo' => 'A.08.03.02','nombre' => 'Eliminación de los medios'),
			array('codigo' => 'A.08.03.03','nombre' => 'Transferencia física de medios'),
			array('codigo' => 'A.09.01.01','nombre' => 'Política de control del acceso'),
			array('codigo' => 'A.09.01.02','nombre' => 'Accesos a las redes y a los servicios de la red'),
			array('codigo' => 'A.09.02.01','nombre' => 'Registro y cancelación de registro de usuario'),
			array('codigo' => 'A.09.02.02','nombre' => 'Asignación de acceso de usuario'),
			array('codigo' => 'A.09.02.03','nombre' => 'Gestión de derechos de acceso privilegiados'),
			array('codigo' => 'A.09.02.04','nombre' => 'Gestión de información secreta de autenticación de usuarios'),
			array('codigo' => 'A.09.02.05','nombre' => 'Revisión de los derechos de acceso de usuario'),
			array('codigo' => 'A.09.02.06','nombre' => 'Eliminación o ajuste de los derechos de acceso'),
			array('codigo' => 'A.09.03.01','nombre' => 'Uso de información de autenticación secreta'),
			array('codigo' => 'A.09.04.01','nombre' => 'Restricción de acceso a la información'),
			array('codigo' => 'A.09.04.02','nombre' => 'Procedimiento de inicio de sesión seguro'),
			array('codigo' => 'A.09.04.03','nombre' => 'Sistema de gestión de contraseñas'),
			array('codigo' => 'A.09.04.04','nombre' => 'Uso de programas utilitarios privilegiados'),
			array('codigo' => 'A.09.04.05','nombre' => 'Control de acceso al código fuente de los programas'),
			array('codigo' => 'A.10.01.01','nombre' => 'Política sobre el uso de controles criptográficos'),
			array('codigo' => 'A.10.01.02','nombre' => 'Gestión de claves'),
			array('codigo' => 'A.11.01.01','nombre' => 'Perímetro de seguridad física'),
			array('codigo' => 'A.11.01.02','nombre' => 'Controles de acceso físico'),
			array('codigo' => 'A.11.01.03','nombre' => 'Seguridad de oficinas, salas e instalaciones'),
			array('codigo' => 'A.11.01.04','nombre' => 'Protección contra amenazas externas y del ambiente'),
			array('codigo' => 'A.11.01.05','nombre' => 'Trabajo en áreas seguras'),
			array('codigo' => 'A.11.01.06','nombre' => 'Áreas de entrega y carga'),
			array('codigo' => 'A.11.02.01','nombre' => 'Ubicación y protección del equipamiento'),
			array('codigo' => 'A.11.02.02','nombre' => 'Elementos de soporte'),
			array('codigo' => 'A.11.02.03','nombre' => 'Seguridad en el cableado'),
			array('codigo' => 'A.11.02.04','nombre' => 'Mantenimiento del equipamiento'),
			array('codigo' => 'A.11.02.05','nombre' => 'Retiro de activos'),
			array('codigo' => 'A.11.02.06','nombre' => 'Seguridad del equipamiento y los activos fuera de las instalaciones'),
			array('codigo' => 'A.11.02.07','nombre' => 'Seguridad en la reutilización o descarte de equipos'),
			array('codigo' => 'A.11.02.08','nombre' => 'Equipo del usuario desatendido'),
			array('codigo' => 'A.11.02.09','nombre' => 'Política de escritorio y pantalla limpios'),
			array('codigo' => 'A.12.01.01','nombre' => 'Procedimientos de operación documentados'),
			array('codigo' => 'A.12.01.02','nombre' => 'Gestión de cambios'),
			array('codigo' => 'A.12.01.03','nombre' => 'Gestión de la capacidad'),
			array('codigo' => 'A.12.01.04','nombre' => 'Separación de los ambientes de desarrollo, prueba y operacionales'),
			array('codigo' => 'A.12.02.01','nombre' => 'Controles contra códigos maliciosos'),
			array('codigo' => 'A.12.03.01','nombre' => 'Respaldo de la información'),
			array('codigo' => 'A.12.04.01','nombre' => 'Registro de evento'),
			array('codigo' => 'A.12.04.02','nombre' => 'Protección de la información de registros'),
			array('codigo' => 'A.12.04.03','nombre' => 'Registros del administrador y el operador'),
			array('codigo' => 'A.12.04.04','nombre' => 'Sincronización de relojes'),
			array('codigo' => 'A.12.05.01','nombre' => 'Instalación del software en sistemas operacionales'),
			array('codigo' => 'A.12.06.01','nombre' => 'Gestión de las vulnerabilidades técnicas'),
			array('codigo' => 'A.12.06.02','nombre' => 'Restricciones sobre la instalación de software'),
			array('codigo' => 'A.12.07.01','nombre' => 'Controles de auditoría de sistemas de información'),
			array('codigo' => 'A.13.01.01','nombre' => 'Controles de red'),
			array('codigo' => 'A.13.01.02','nombre' => 'Seguridad de los servicios de red'),
			array('codigo' => 'A.13.01.03','nombre' => 'Separación en las redes'),
			array('codigo' => 'A.13.02.01','nombre' => 'Políticas y procedimientos de transferencia de información'),
			array('codigo' => 'A.13.02.02','nombre' => 'Acuerdos sobre transferencia de información'),
			array('codigo' => 'A.13.02.03','nombre' => 'Mensajería electrónica'),
			array('codigo' => 'A.13.02.04','nombre' => 'Acuerdos de confidencialidad o no divulgación'),
			array('codigo' => 'A.14.01.01','nombre' => 'Análisis y especificación de requisitos de seguridad de la información'),
			array('codigo' => 'A.14.01.02','nombre' => 'Aseguramiento de servicios de aplicación en redes públicas'),
			array('codigo' => 'A.14.01.03','nombre' => 'Protección de las transacciones de servicios de aplicación'),
			array('codigo' => 'A.14.02.01','nombre' => 'Política de desarrollo seguro'),
			array('codigo' => 'A.14.02.02','nombre' => 'Procedimientos de control de cambios'),
			array('codigo' => 'A.14.02.03','nombre' => 'Revisión técnica de las aplicaciones después de los cambios en la plataforma de operación'),
			array('codigo' => 'A.14.02.04','nombre' => 'Restricciones en los cambios a los paquetes de software'),
			array('codigo' => 'A.14.02.05','nombre' => 'Principios de ingeniería de sistema seguro'),
			array('codigo' => 'A.14.02.06','nombre' => 'Entorno de desarrollo seguro'),
			array('codigo' => 'A.14.02.07','nombre' => 'Desarrollo tercerizado'),
			array('codigo' => 'A.14.02.08','nombre' => 'Prueba de seguridad del sistema'),
			array('codigo' => 'A.14.02.09','nombre' => 'Prueba de aprobación del sistema'),
			array('codigo' => 'A.14.03.01','nombre' => 'Protección de datos de prueba'),
			array('codigo' => 'A.15.01.01','nombre' => 'Política de seguridad de la información para las relaciones con el proveedor'),
			array('codigo' => 'A.15.01.02','nombre' => 'Abordar la seguridad dentro de los acuerdos del proveedor'),
			array('codigo' => 'A.15.01.03','nombre' => 'Cadena de suministro de tecnologías de la información y comunicaciones'),
			array('codigo' => 'A.15.02.01','nombre' => 'Supervisión y revisión de los servicios del proveedor'),
			array('codigo' => 'A.15.02.02','nombre' => 'Gestión de cambios a los servicios del proveedor'),
			array('codigo' => 'A.16.01.01','nombre' => 'Responsabilidades y procedimientos'),
			array('codigo' => 'A.16.01.02','nombre' => 'Informe de eventos de seguridad de la información'),
			array('codigo' => 'A.16.01.03','nombre' => 'Informe de las debilidades de seguridad de la información'),
			array('codigo' => 'A.16.01.04','nombre' => 'Evaluación y decisión sobre los eventos de seguridad de la información'),
			array('codigo' => 'A.16.01.05','nombre' => 'Respuesta ante incidentes de seguridad de la información'),
			array('codigo' => 'A.16.01.06','nombre' => 'Aprendizaje de los incidentes de seguridad de la información'),
			array('codigo' => 'A.16.01.07','nombre' => 'Recolección de evidencia'),
			array('codigo' => 'A.17.01.01','nombre' => 'Planificación de la continuidad de la seguridad de la información'),
			array('codigo' => 'A.17.01.02','nombre' => 'Implementación de la continuidad de la seguridad de la información'),
			array('codigo' => 'A.17.01.03','nombre' => 'Verificación, revisión y evaluación de la continuidad de la seguridad de la información'),
			array('codigo' => 'A.17.02.01','nombre' => 'Disponibilidad de las instalaciones de procesamiento de la información'),
			array('codigo' => 'A.18.01.01','nombre' => 'Identificación de la legislación vigente y los requisitos contractuales'),
			array('codigo' => 'A.18.01.02','nombre' => 'Derechos de propiedad intelectual'),
			array('codigo' => 'A.18.01.03','nombre' => 'Protección de los registros'),
			array('codigo' => 'A.18.01.04','nombre' => 'Privacidad y protección de la información de identificación personal'),
			array('codigo' => 'A.18.01.05','nombre' => 'Regulación de los controles criptográficos'),
			array('codigo' => 'A.18.02.01','nombre' => 'Revisión independiente de la seguridad de la información'),
			array('codigo' => 'A.18.02.02','nombre' => 'Cumplimiento con las políticas y normas de seguridad'),
			array('codigo' => 'A.18.02.03','nombre' => 'Verificación del cumplimiento técnico')
		));
        
		
	}

}

?>