<?php

class InstitucionesTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		DB::table('instituciones')->insert(array(
		  	array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'COMISION NACIONAL DE RIEGO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'CORPORACION NACIONAL FORESTAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'INSTITUTO DE DESARROLLO AGROPECUARIO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'OFICINA DE ESTUDIOS Y POLITICAS AGRARIAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'SERVICIO AGRICOLA Y GANADERO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE AGRICULTURA','servicio' =>'SUBSECRETARIA DE AGRICULTURA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE BIENES NACIONALES','servicio' =>'SUBSECRETARIA DE BIENES NACIONALES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DEFENSA NACIONAL','servicio' =>'DIRECCION GENERAL DE AERONAUTICA CIVIL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DEFENSA NACIONAL','servicio' =>'SUBSECRETARÍA DE DEFENSA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DEFENSA NACIONAL','servicio' =>'SUBSECRETARÍA PARA LAS FUERZAS ARMADAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'CORPORACION NACIONAL DE DESARROLLO INDIGENA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'FONDO DE SOLIDARIDAD E INVERSION SOCIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'INSTITUTO NACIONAL DE LA JUVENTUD','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'SERVICIO NACIONAL DE DISCAPACIDAD','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'SERVICIO NACIONAL DEL ADULTO MAYOR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'SUBSECRETARÍA DE EVALUACIÓN SOCIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE DESARROLLO SOCIAL','servicio' =>'SUBSECRETARIA DE SERVICIOS SOCIALES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'AGENCIA DE PROMOCIÓN DE LA INVERSIÓN EXTRANJERA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'CORPORACION DE FOMENTO DE LA PRODUCCION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'FISCALIA NACIONAL ECONOMICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'INSTITUTO NACIONAL DE ESTADISTICAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'INSTITUTO NACIONAL DE PROPIEDAD INDUSTRIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SERVICIO DE COOPERACION TECNICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SERVICIO NACIONAL DE PESCA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SERVICIO NACIONAL DE TURISMO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SERVICIO NACIONAL DEL CONSUMIDOR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SUBSECRETARIA DE ECONOMIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SUBSECRETARIA DE PESCA Y ACUICULTURA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ECONOMIA, FOMENTO Y TURISMO','servicio' =>'SUPERINTENDENCIA DE INSOLVENCIA Y REEMPRENDIMIENTO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'AGENCIA DE CALIDAD DE LA EDUCACIÓN','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'COMISION NACIONAL DE INVESTIGACION CIENTIFICA Y TECNOLOGICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'CONSEJO NACIONAL DE EDUCACION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'CONSEJO NACIONAL DE LA CULTURA Y DE LAS ARTES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'DIRECCION DE BIBLIOTECAS ARCHIVOS Y MUSEOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'JUNTA NACIONAL DE AUXILIO ESCOLAR Y BECAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'JUNTA NACIONAL DE JARDINES INFANTILES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'SUBSECRETARIA DE EDUCACION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE EDUCACION','servicio' =>'SUPERINTENDENCIA DE EDUCACIÓN','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ENERGIA','servicio' =>'COMISION CHILENA DE ENERGIA NUCLEAR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ENERGIA','servicio' =>'COMISION NACIONAL DE ENERGIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ENERGIA','servicio' =>'SUBSECRETARIA DE ENERGIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE ENERGIA','servicio' =>'SUPERINTENDENCIA DE ELECTRICIDAD Y COMBUSTIBLES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'CONSEJO DE DEFENSA DEL ESTADO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'DIRECCION DE COMPRAS Y CONTRATACION PUBLICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'DIRECCION DE PRESUPUESTOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL Ministerio de Hacienda','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SERVICIO DE TESORERIAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SERVICIO NACIONAL DE ADUANAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SUPERINTENDENCIA DE BANCOS E INSTITUCIONES FINANCIERAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SUPERINTENDENCIA DE CASINOS DE JUEGO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'SUPERINTENDENCIA DE VALORES Y SEGUROS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'UNIDAD DE ANALISIS FINANCIERO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE HACIENDA','servicio' =>'DIRECCION NACIONAL DEL SERVICIO CIVIL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'DEFENSORIA PENAL PUBLICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'GENDARMERIA DE CHILE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL Ministerio de Justicia','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'SERVICIO DE REGISTRO CIVIL E IDENTIFICACION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'SERVICIO MEDICO LEGAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE JUSTICIA Y DERECHOS HUMANOS','servicio' =>'SERVICIO NACIONAL DE MENORES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE LA MUJER Y LA EQUIDAD DE GÉNERO','servicio' =>'SERVICIO NACIONAL DE LA MUJER','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE MINERIA','servicio' =>'COMISION CHILENA DEL COBRE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE MINERIA','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL Ministerio de Mineria','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE MINERIA','servicio' =>'SERVICIO NACIONAL DE GEOLOGIA Y MINERIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE AEROPUERTOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE ARQUITECTURA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE CONTABILIDAD Y FINANZAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE OBRAS HIDRAULICAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE OBRAS PORTUARIAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE PLANEAMIENTO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION DE VIALIDAD','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION GENERAL DE AGUAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'DIRECCION GENERAL DE OBRAS PUBLICAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'FISCALIA DE OBRAS PUBLICAS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'INSTITUTO NACIONAL DE HIDRAULICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL Ministerio de Obras Publicas','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE OBRAS PUBLICAS','servicio' =>'SUPERINTENDENCIA DE SERVICIOS SANITARIOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE RELACIONES EXTERIORES','servicio' =>'AGENCIA DE COOPERACION INTERNACIONAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE RELACIONES EXTERIORES','servicio' =>'DIRECCION DE FRONTERAS Y LIMITES DEL ESTADO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE RELACIONES EXTERIORES','servicio' =>'DIRECCION GENERAL DE RELACIONES ECONOMICAS INTERNACIONALES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE RELACIONES EXTERIORES','servicio' =>'INSTITUTO ANTARTICO CHILENO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE RELACIONES EXTERIORES','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL Y SERVICIO EXTERIOR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE SALUD','servicio' =>'CENTRAL DE ABASTECIMIENTOS DEL S.N.S.S.','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE SALUD','servicio' =>'FONDO NACIONAL DE SALUD','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE SALUD','servicio' =>'INSTITUTO DE SALUD PUBLICA DE CHILE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE SALUD','servicio' =>'SUBSECRETARIA DE REDES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE SALUD','servicio' =>'SUBSECRETARIA DE SALUD PUBLICA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE TRANSPORTE Y TELECOMUNICACIONES','servicio' =>'JUNTA DE AERONAUTICA CIVIL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE TRANSPORTE Y TELECOMUNICACIONES','servicio' =>'SECRETARIA Y ADMINISTRACION GENERAL DE TRANSPORTES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE TRANSPORTE Y TELECOMUNICACIONES','servicio' =>'SUBSECRETARIA DE TELECOMUNICACIONES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'PARQUE METROPOLITANO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION I REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION II REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION III REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION IV REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION IX REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION METROPOLITANO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION V REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION VI REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION VII REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION VIII REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION X REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION XI REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION XII REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION XIV REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SERVICIO REGIONAL DE VIVIENDA Y URBANIZACION XV REGION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DE VIVIENDA Y URBANISMO','servicio' =>'SUBSECRETARIA DE VIVIENDA Y URBANISMO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL DEPORTE','servicio' =>'INSTITUTO NACIONAL DE DEPORTES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION I TARAPACA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION II ANTOFAGASTA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION III ATACAMA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION IV COQUIMBO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION IX ARAUCANIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION METROPOLITANA DE SANTIAGO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION V VALPARAISO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION VI LIBERTADOR GENERAL BERNARDO O´HIGGINS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION VII MAULE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION VIII BIO BIO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION X LOS LAGOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION XI AYSEN DEL GRAL. CARLOS IBAÑEZ DEL CAMPO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION XII MAGALLANES Y ANTARTICA CHILENA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION XIV DE LOS RIOS','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'GOBIERNO REGIONAL REGION XV DE ARICA Y PARINACOTA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'OFICINA NACIONAL DE EMERGENCIA','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'SERVICIO DE GOBIERNO INTERIOR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'SERVICIO NACIONAL PARA PREVENCION Y REHABILITACION CONSUMO DE DROGAS Y ALCOHOL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'SUBSECRETARIA DE DESARROLLO REGIONAL Y ADMINISTRATIVO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'SUBSECRETARIA DE PREVENCION DEL DELITO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL INTERIOR Y SEGURIDAD PÚBLICA','servicio' =>'SUBSECRETARIA DEL INTERIOR','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL MEDIO AMBIENTE','servicio' =>'SERVICIO DE EVALUACION AMBIENTAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL MEDIO AMBIENTE','servicio' =>'SUBSECRETARIA DEL MEDIO AMBIENTE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL MEDIO AMBIENTE','servicio' =>'SUPERINTENDENCIA DEL MEDIO AMBIENTE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'CAJA DE PREVISION DE LA DEFENSA NACIONAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'DIRECCION DE PREVISION DE CARABINEROS DE CHILE','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'DIRECCION DEL TRABAJO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'DIRECCION GENERAL DE CREDITO PRENDARIO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'INSTITUTO DE PREVISION SOCIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'INSTITUTO DE SEGURIDAD LABORAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'SERVICIO NACIONAL DE CAPACITACION Y EMPLEO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'SUBSECRETARIA DE PREVISION SOCIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'SUBSECRETARIA DEL TRABAJO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'SUPERINTENDENCIA DE PENSIONES','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO DEL TRABAJO Y PREVISION SOCIAL','servicio' =>'SUPERINTENDENCIA DE SEGURIDAD SOCIAL','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO SECRETARIA GENERAL DE GOBIERNO','servicio' =>'CONSEJO NACIONAL DE TELEVISION','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO SECRETARIA GENERAL DE GOBIERNO','servicio' =>'SECRETARIA GENERAL DE GOBIERNO','estado' =>'ingresado'),
			array('ministerio' =>'MINISTERIO SECRETARIA GENERAL DE LA PRESIDENCIA','servicio' =>'SECRETARIA GENERAL DE LA PRESIDENCIA DE LA REPUBLICA','estado' =>'ingresado'),
			array('ministerio' =>'PRESIDENCIA DE LA REPUBLICA','servicio' =>'DIRECCION ADMINISTRATIVA PRESIDENCIA DE LA REPUBLICA','estado' =>'ingresado')
		));
        
		
	}

}

?>